[package]
name = "day19"
version = "0.1.0"
edition = "2021"

[dependencies]
global = {path = "../global"}
parse-display = "0.8.0"
priority-queue = "1.3.0"

[[bin]]
name = "day19a"

[[bin]]
name = "day19b"